A company started to invest in digital marketing as a new way of their product
promotions.For that they collected data and decided to carry out a study on it.

● The company wishes to clarify whether there is any increase in sales after
stepping into digital marketing.

● The company needs to check whether there is any dependency between the
features “Region” and “Manager”.

Help the company to carry out their study with the help of data provided

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#read the data
data=pd.read_csv('Downloads/Sales_add.csv')
data.head()


Month      Region      Manager  Sales_before_digital_add(in $)  \
0  Month-1  Region - A  Manager - A                          132921   
1  Month-2  Region - A  Manager - C                          149559   
2  Month-3  Region - B  Manager - A                          146278   
3  Month-4  Region - B  Manager - B                          152167   
4  Month-5  Region - C  Manager - B                          159525   

   Sales_After_digital_add(in $)  
0                         270390  
1                         223334  
2                         244243  
3                         231808  
4                         258402

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   Month                           22 non-null     object
 1   Region                          22 non-null     object
 2   Manager                         22 non-null     object
 3   Sales_before_digital_add(in $)  22 non-null     int64 
 4   Sales_After_digital_add(in $)   22 non-null     int64 
dtypes: int64(2), object(3)
memory usage: 1008.0+ bytes


In [50]:
data.describe()

Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
count                       22.000000                      22.000000
mean                    149239.954545                  231123.727273
std                      14844.042921                   25556.777061
min                     130263.000000                  187305.000000
25%                     138087.750000                  214960.750000
50%                     147444.000000                  229986.500000
75%                     157627.500000                  250909.000000
max                     178939.000000                  276279.000000

# To check whether there is any increase in sales after stepping into digital marketing.

In [53]:
x=data['Sales_before_digital_add(in $)']
y=data['Sales_After_digital_add(in $)']

In [54]:
print(np.var(x), np.var(y))

210329900.67975205 623460269.4710745


In [55]:
print(np.var(y)/np.var(x))

2.9642017965878944


In [56]:
#set hypothesis

Null Hypothesis: µ1 >= µ2 (Average sales before digital add is greater than or equal to that of the average  sales after digital adds)

Alternative Hypothesis: µ1 < µ2 (Average sales before digital add is greater than or equal that of the average  sales after digital adds)

In [57]:
import scipy.stats as stats
stats.ttest_ind(x, y, equal_var=True)

Ttest_indResult(statistic=-12.995084451110877, pvalue=2.614368006904645e-16)

Insight-

Here P-Value is less than 0.05(alpha).So we reject the null hypothesis.Thereore the average sales has increased after using the 
digital adds

# To check whether there is any dependency between the features “Region” and “Manager”


In [58]:
#set hypothesis

H0 = There is no dependency between the features “Region” and “Manager”

H1 = There is a dependency between the features “Region” and “Manager”

In [59]:
data1=pd.crosstab(data['Region'],data['Manager'])
print(data1)

Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1


In [60]:
#observed values
observed_values=data1.values
print('observed values are :',observed_values)

observed values are : [[4 3 3]
 [4 1 2]
 [1 3 1]]


In [61]:
val=stats.chi2_contingency(data1)
val

(3.050566893424036,
 0.5493991051158094,
 4,
 array([[4.09090909, 3.18181818, 2.72727273],
        [2.86363636, 2.22727273, 1.90909091],
        [2.04545455, 1.59090909, 1.36363636]]))

In [62]:
expected_values=val[3]

In [63]:
no_of_rows=len(data.iloc[0:3,0])
no_of_columns=len(data.iloc[0,0:3])
ddof=(no_of_rows-1)*(no_of_columns-1)
print('Degree of freedom:',ddof)
alpha=0.05

Degree of freedom: 4


In [64]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(observed_values,expected_values)])
chi_square_statistic=chi_square[0]+chi_square[1]
print('chi-square statistic :',chi_square_statistic)

chi-square statistic : 2.921995464852608


In [65]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical value:',critical_value)

critical value: 9.487729036781154


In [66]:
#p value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('P-value :',p_value)
print('Significance level :',alpha)
print('Degree of Freedom :',ddof)

P-value : 0.5709629929220089
Significance level : 0.05
Degree of Freedom : 4


In [67]:
if chi_square_statistic>=critical_value:
    print('Reject H0,there is a dependency between the features Region and Manager')
else:
    print('Retain H0,there is no dependency between the features Region and Manager')
if p_value<=alpha:
     print('Reject H0,there is a dependency between the features Region and Manager')
else:
    print('Retain H0,there is no dependency between the features Region and Manager')        
    


Retain H0,there is no dependency between the features Region and Manager
Retain H0,there is no dependency between the features Region and Manager
